const AMOUNT_OF_POINTS = 3;
const POINT_TYPES = ['Taxi', 'Bus', 'Train', 'Ship', 'Drive', 'Flight', 'Check-in', 'Sightseeing', 'Restaurant'];


const DATE_YEAR_MOUNTH_DAY_FORMAT = 'YYYY-MM-DD';
const DATE_MOUNTH_DAY_FORMAT = 'MMM D';
const DATE_HOURS_MINUTE_FORMAT = 'HH:mm';
const DATE_DAY_MOUNTH_YEAR_HOUR_MINUTE_FORMAT = 'DD/MM/YY HH:mm';

export { AMOUNT_OF_POINTS, POINT_TYPES, DATE_YEAR_MOUNTH_DAY_FORMAT, DATE_MOUNTH_DAY_FORMAT, DATE_HOURS_MINUTE_FORMAT, DATE_DAY_MOUNTH_YEAR_HOUR_MINUTE_FORMAT };
